name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Test
        env:
          PORT: ${{secrets.PORT}}
        run: npm run test
  my:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sudo apt update && sudo apt install -y npm
      - run: npm install --global fast-cli
      - name: run
        run: fast --upload
